---
- name: Filter unreachable
  hosts: vm:ct:node:!ignored
  gather_facts: no
  tasks:
  - name: Check reachable
    no_log: yes
    ping:

- name: Update
  hosts: vm:ct:node:!ignored
  module_defaults:
    setup:
      gather_subset: "!all"
  gather_facts: yes
  tasks:
  - include_role:
      name: update

- name: Fix proxmox after update
  hosts: proxmox:!ignored
  tasks:
  - include_role:
      name: proxmox
