---
- name: apt update
  tags:
  - update
  ansible.builtin.apt:
    #force_apt_get: yes
    update_cache: yes
    upgrade: full
    autoremove: yes
    autoclean: yes
    clean: yes
- name: Check reboot
  tags:
  - reboot
  stat:
    path: /var/run/reboot-required
  register: p
- name: Reboot
  # Note: Does not work for containers
  reboot:
  when:
  - p.stat.exists
  - no_reboot is not defined or not no_reboot
