---

- name: Manage Apache
  tags: always
  notify: Reload apache
  block:
  - name: Install apache
    package:
      name: apache2
      state: present

  - name: Disable apache2 modules
    apache2_module:
      name: "{{ item }}"
      state: absent
      warn_mpm_absent: no
    with_items:
    - mpm_itk
    - mpm_prefork
    - mpm_worker

  - name: Enable apache2 modules
    apache2_module:
      name: "{{ item }}"
    with_items:
    - mpm_event
    - actions
    - rewrite

  - name: Set up site config
    vars:
      site: "{{ item }}"
    template_config:
      src: site.conf.j2
      dest: /etc/apache2/sites-enabled/{{ item.name }}.conf
      owner: www-data
      group: www-data
      lstrip_blocks: yes
      validate: apachectl -t
    loop: "{{ domains }}"
    loop_control:
      label: "{{ item.name }}"

  - name: remoteip
    import_tasks: remoteip.yml

  - name: phpmyadmin
    import_tasks: phpmyadmin.yml

  - name: statistics
    import_tasks: statistics.yml
