---

- name: Install packages
  package:
    name:
    - nginx
    - certbot
    - "{{ 'python3-' if (ansible_pkg_mgr | lower) == 'apt' else '' }}certbot-nginx"
    state: present

- name: Find existing configs
  find:
    paths: /etc/nginx/http.d
    patterns: "*.conf"
  register: configs

- name: Set new facts
  vars:
    prev_config: "{{ configs.files | map(attribute='path') | map('basename') }}"
    curr_config: "{{ proxies | map(attribute='name') | product(['.conf']) | map('join') }}"
  set_fact:
    remove_config: "{{ prev_config | difference(curr_config) | difference(['security.conf', 'default.conf']) }}"

- name: Remove old config
  file:
    state: absent
    path: /etc/nginx/http.d/{{ item }}
  loop: "{{ remove_config }}"

- name: Install security SSL
  copy:
    src: security.conf
    dest: /etc/nginx/http.d/security.conf
    owner: root
    group: root

- name: Make sure certbot runs once a day
  block:
  - name: Enable systemd timer
    systemd:
      name: certbot.timer
      state: started
      enabled: yes
    when: "'systemd' == ansible_service_mgr"
  - name: Enable cronjob
    cron:
      name: certbot-renewal
      job: /bin/sh -lc '/usr/bin/certbot -q renew'
      minute: "0"
      hour: "14"
    when: "'openrc' == ansible_service_mgr"

- name: Create ACME account
  command: /usr/bin/certbot -n register --agree-tos --email {{ web_cert_email }}
  args:
    # Avoid trying to register twice
    creates: /etc/letsencrypt/accounts
  when: web_cert_email is defined

- name: Install certificates
  command: >-
    /usr/bin/certbot -n --nginx certonly -d {{ item.name }}
    {{ [item.alias | default([])] | flatten | product(['-d ']) | map('join') | join(" ") }}
    {{ "--dry-run" if ansible_check_mode else "" }}
  args:
    creates: /etc/letsencrypt/live/{{ item.name }}
  loop: "{{ proxies }}"
  loop_control:
    label: "{{ item.name }}"
  notify: restart nginx

- name: Install configs
  vars:
    site: "{{ item }}"
  template_config:
    src: proxy.conf.j2
    dest: /etc/nginx/http.d/{{ item.name }}.conf
    owner: root
    group: root
    lstrip_blocks: yes
    validate: nginx -t
  loop: "{{ proxies }}"
  loop_control:
    label: "{{ item.name }}"
  notify: restart nginx

