---
- name: Launch correct distro
  tags:
  - always
  block:
  - include_tasks: "pkg_mgr/{{ ansible_pkg_mgr | lower }}.yml"
  # TODO: Find a better way to handle this
  - name: Check for services
    no_log: yes
    ignore_errors: yes
    service_facts:
    #when: "(ansible_os_family | lower) not in ['ansible', 'alpine']"
  - name: Make sure qemu-guest-agent have started
    service:
      name: qemu-guest-agent
      state: started
    when: "services is defined and 'qemu-guest-agent' in services"
