---
- name: VyOS
  vars:
    router_vyos_system: "{{ router_system }}"
    router_vyos_interfaces: "{{ router_interfaces }}"
    router_vyos_services: "{{ router_services }}"
    router_vyos_key: "{{ router_key }}"
    router_vyos_dhcpv4: "{{ router_dhcpv4 | vyos_dhcp(hostvars) }}"
    nat:
      destination: "{{ hostvars.values() | selectattr('nat', 'defined') | vyos_nat_combine }}"
      source: "{{ router_snat | default([]) }}"
    router_vyos_nat: "{{ nat | vyos_nat(router_interface.WAN) }}"
    firewall:
      groups: "{{ router_firewall_config | default(omit) }}"
      rules: "{{ router_firewall_rules | default(omit) }}"
      #interfaces: "{{ router_firewall_interfaces | default(omit) }}"
      #forward: "{{ router_firewall_forward | default(omit) }}"
    router_vyos_firewall: "{{ firewall | vyos_firewall }}"
    router_vyos_firewall_config: "{{ router_firewall_config }}"
    router_vyos_firewall_rules: "{{ router_firewall_rules }}"
    router_vyos_firewall_interfaces: "{{ router_firewall_interfaces }}"
    router_vyos_containers: "{{ router_containers }}"
  import_role:
    name: vyos
